version: '3.8'

services:
  kpi-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: kpi-service
    container_name: kpi-service
    ports:
      - "8010:8010"
    environment:
      - SERVER_PORT=8010
      - SPRING_APPLICATION_NAME=kpi-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
    networks:
      - devsecops-network

networks:
  devsecops-network:
    external: true
